# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "rpool/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/8C22-4BAC";
      fsType = "vfat";
    };

  fileSystems."/media/bulk" =
    {
      device = "/dev/disk/by-uuid/f762410f-9fb0-47b5-adfa-f83c08081916";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/98ebd164-9fbe-409e-94f0-2f7a7865e298"; }];

}
